//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowStretch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Ver {
            get {
                return ((int)(this["Ver"]));
            }
            set {
                this["Ver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullScreen")]
        public global::WindowStretch.Core.StretchMode WideMode {
            get {
                return ((global::WindowStretch.Core.StretchMode)(this["WideMode"]));
            }
            set {
                this["WideMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WideAlwaysTop {
            get {
                return ((bool)(this["WideAlwaysTop"]));
            }
            set {
                this["WideAlwaysTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaxOnDesktop")]
        public global::WindowStretch.Core.StretchMode TallMode {
            get {
                return ((global::WindowStretch.Core.StretchMode)(this["TallMode"]));
            }
            set {
                this["TallMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TallAlwaysTop {
            get {
                return ((bool)(this["TallAlwaysTop"]));
            }
            set {
                this["TallAlwaysTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WideAllowExcess {
            get {
                return ((bool)(this["WideAllowExcess"]));
            }
            set {
                this["WideAllowExcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TallAllowExcess {
            get {
                return ((bool)(this["TallAllowExcess"]));
            }
            set {
                this["TallAllowExcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dmmgameplayer://umamusume/cl/general/umamusume")]
        public string StartAppUri {
            get {
                return ((string)(this["StartAppUri"]));
            }
            set {
                this["StartAppUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartWithMe {
            get {
                return ((bool)(this["StartWithMe"]));
            }
            set {
                this["StartWithMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShotSaveFolder {
            get {
                return ((string)(this["ShotSaveFolder"]));
            }
            set {
                this["ShotSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShotOpenViewer {
            get {
                return ((bool)(this["ShotOpenViewer"]));
            }
            set {
                this["ShotOpenViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecordSaveFolder {
            get {
                return ((string)(this["RecordSaveFolder"]));
            }
            set {
                this["RecordSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScaleEnabled {
            get {
                return ((bool)(this["ScaleEnabled"]));
            }
            set {
                this["ScaleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<RectangleF xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Location>
    <X>0.3075</X>
    <Y>0.111</Y>
  </Location>
  <Size>
    <Width>0.4054</Width>
    <Height>0.031</Height>
  </Size>
  <X>0.3075</X>
  <Y>0.111</Y>
  <Width>0.4054</Width>
  <Height>0.031</Height>
</RectangleF>")]
        public global::System.Drawing.RectangleF ScaleRect {
            get {
                return ((global::System.Drawing.RectangleF)(this["ScaleRect"]));
            }
            set {
                this["ScaleRect"] = value;
            }
        }
    }
}
